/*1. Navigate to https://leafground.com/checkbox.xhtml 
2. Click on the "Basic Checkbox.” 
3. Click on the "Notification Checkbox." 
4. Verify that the expected message is displayed. 
5. Click on your favorite language (assuming it's related to checkboxes). 
6. Click on the "Tri-State Checkbox." 
7. Verify which tri-state option has been chosen. 
8. Click on the "Toggle Switch." 
9. Verify that the expected message is displayed. 
10. Verify if the Checkbox is disabled. 
11. Select multiple options on the page (details may be needed). 
12. Perform any additional actions or verifications required. 
13. Close the web browser when done. */




import { expect, test } from "@playwright/test";

test("Leafground checkbox in Playwright", async ({ page }) => {
    await page.goto("https://leafground.com/checkbox.xhtml");

    // Basic Checkbox
    await page.getByText("Basic", { exact: true }).click();

    // Notification Checkbox (Ajax)
    await page.getByText("Ajax", { exact: true }).click();

    const notificationAlert = page.locator(".ui-growl-message");
    await expect(notificationAlert.locator(".ui-growl-title")).toHaveText("Checked");

    // Favorite language
    await page.getByText("C-Sharp", { exact: true }).click();

    // Tri-State Checkbox
    // const triStateCheckbox = page.locator(".ui-tristatechkbox .ui-chkbox-box");
    // await triStateCheckbox.click();
    // Tri-State Checkbox
        const triStateCard = page.locator(".card", {
            has: page.getByText("Tri State Checkbox", { exact: true }),
        });

        const triStateCheckbox = triStateCard.locator(".ui-chkbox-box");

        await expect(triStateCheckbox).toBeVisible();
        await triStateCheckbox.click();

    // Verify the alert generated by Tri-State Checkbox.
    const stateAlert = page.locator(".ui-growl-message", {
        has: page.locator(".ui-growl-title", {
            hasText: "State has been changed.",
        }),
    });

    await expect(stateAlert).toBeVisible();
    await expect(stateAlert.locator(".ui-growl-title")).toHaveText(
        "State has been changed."
    );
    await expect(stateAlert.locator("p")).toHaveText("State = 1");
});

// Click on the "Toggle Switch." 
// 9. Verify that the expected message is displayed. 
// 10. Verify if the Checkbox is disabled. 
// 11. Select multiple options on the page (details may be needed). 
// 12. Perform any additional actions or verifications required. 
// 13. Close the web browser when done. */


// import { expect, test } from "@playwright/test";

// test("Leafground checkbox in Playwright", async ({ page }) => {
//     await page.goto("https://leafground.com/checkbox.xhtml ");
//     await page.locator('//div[@class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"]').first().click();
//     await page.locator('//div[@class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"]').nth(0).click();
//     // Assert the  alert title.
//     const alertMessage = page.locator(".ui-growl-message .ui-growl-title");
//     await expect(alertMessage).toBeVisible();
//     await expect(alertMessage).toHaveText("Checked");
//     //Click on your favorite language (assuming it's related to checkboxes). 
//     //await page.getByRole("checkbox",{name:"C-Sharp",exact:true}).click();
//     await page.locator('//div[@class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"]').nth(3).click();
//     await page.locator('//div[@class="ui-chkbox-box ui-widget ui-corner-all ui-state-default"]').nth(4).click();
//     //expect (triStateCheckBox).
//     //await page.waitForTimeout(5000);


//     /* ...existing code... */

//     // Click the Tri-State Checkbox and verify its selected state.
//     //const triStateCheckBox = page.locator(".ui-tristatechkbox .ui-chkbox-box");

//     //await triStateCheckBox.click();

//     // // ...existing code...

//     // Alert displayed after the Tri-State checkbox changes.
//     const stateAlert = page.locator(".ui-growl-message", {
//                 has: page.locator(".ui-growl-title", { hasText: "State has been changed." }),
//             });

//         //     await expect(stateAlert).toBeVisible();
//         //     await expect(stateAlert.locator(".ui-growl-title")).toHaveText("State has been changed.");
//         //     await expect(stateAlert.locator("p")).toHaveText("State = 1");

//         // // ...existing code...

//     // First click selects the "Checked" state.
//     // const stateAlertMessage = page.locator('//span[@class="ui-growl-title"]');
//     // await expect (stateAlertMessage).toBeVisible();
//     // await expect(stateAlertMessage).toContainText(`State has been changed.`);

//     // ...remove await page.waitForTimeout(5000);
//     const stateAlertTitle = page.locator(
//             '//div[contains(@class,"ui-growl-message")]//span[@class="ui-growl-title"]'
//         );
//         const selectedState = page.locator(
//             '//div[contains(@class,"ui-growl-message")]//p'
//         );

//         await expect(stateAlertTitle).toHaveText("State has been changed.");
//         await expect(selectedState).toHaveText("State = 1");

// /* ...existing code... */



// });